# Generated by Django 4.1.5 on 2023-01-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grape_quiz', '0002_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default='', max_length=80),
        ),
    ]
