# Generated by Django 4.1.5 on 2023-01-14 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grape_quiz', '0004_remove_question_slug_remove_quiz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grape_quiz.question'),
        ),
    ]
